<div<?php
    echo ' class="'.$this->getClassname().'"';
    if ($this->getDisplayDays()) {
        echo ' data-display-days="1"';
    }
    if ($this->hasData('date')) {
        echo ' data-end-datetime-utc="'.$this->getDateInTimestamp().'"';
    }
    if (!$this->hasData('date') && $this->getSecondsLeft()) {
        echo ' data-seconds-left="'.$this->getSecondsLeft().'"';
    }
    if ($this->getInlinestyle()) {
        echo ' style="'.$this->getInlinestyle().'"';
    }
?>>
    <span class="days"></span>
</div>
