<?php
  $helper = $this->helper('Swissup\Countdowntimer\Helper\Data');
?>
<script type="text/javascript">
  function setAttributeSecondsLeft(htmlObj) {
    if (htmlObj.hasAttribute('data-end-datetime-utc')) {
      var secondsLeft = parseInt(htmlObj.getAttribute('data-end-datetime-utc'));
      secondsLeft -= Math.floor(Date.now() / 1000);
      if (secondsLeft < 0) {secondsLeft = 0};
      htmlObj.setAttribute('data-seconds-left', secondsLeft);
    };
  }
  function setDaysForSimpleTimer(htmlObj) {
    if (!htmlObj.hasAttribute('data-display-days')) { return; };
    var secondsLeft = parseInt(htmlObj.getAttribute('data-seconds-left'));
    var numberOfDays = Math.floor( secondsLeft / ( 24 * 60 * 60 ) );
    if (numberOfDays > 0) {
      jQuery(htmlObj).find('.days').text(numberOfDays.toString() + ' ' + Translator.translate('day(s)'));
      secondsLeft -= numberOfDays * 24 * 60 * 60;
      htmlObj.setAttribute('data-seconds-left', secondsLeft);
    } else {
      jQuery(htmlObj).find('.days').text('');
    };
  }
  var timerSimpleClass = '.<?php echo \Swissup\Countdowntimer\Block\SimpleTimer::getTimerBaseClass() ?>';
  var timerFlipClass = '.<?php echo \Swissup\Countdowntimer\Block\FlipTimer::getTimerBaseClass() ?>';
  var localeName = '<?php echo $helper->getLocale(); ?>';
  // start flip timers
  require([
      'flipclock'
  ], function () {
  jQuery(timerFlipClass).each(
    function (index, htmlObj) {
      setAttributeSecondsLeft(htmlObj);
      jQuery(this).FlipClock(
        htmlObj.getAttribute('data-seconds-left'),
        {
          clockFace: htmlObj.getAttribute('data-flipface'),
          countdown: true//,
          //language: localeName
        }
      )
    }
  );
  });
  // start simple timers
  require([
    'simpletimer'
  ], function () {
    jQuery(timerSimpleClass).each(
      function (index, htmlObj) {
        setAttributeSecondsLeft(htmlObj);
        setDaysForSimpleTimer(htmlObj);
      }
    ).startTimer();
  });
</script>
